export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE';

export const REGISTER_NEW_CART = "REGISTER_NEW_CART";
export const REGISTER_NEW_CART_SUCCESS = "REGISTER_NEW_CART_SUCCESS";
export const REGISTER_NEW_CART_FAIL = "REGISTER_NEW_CART_FAIL";